// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPmG0YbhTFy8S3apjW7ELbx3IA9P_P6BY',
    appId: '1:778060752352:web:fc35fb94cbe6527708b785',
    messagingSenderId: '778060752352',
    projectId: 'onlycars-c1fd0',
    authDomain: 'onlycars-c1fd0.firebaseapp.com',
    storageBucket: 'onlycars-c1fd0.firebasestorage.app',
    measurementId: 'G-1PJP16X4W1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0hZJ6J9dpe6YDo1X1369BnupT10n_3P4',
    appId: '1:778060752352:android:80b5732d3cf0a7d108b785',
    messagingSenderId: '778060752352',
    projectId: 'onlycars-c1fd0',
    storageBucket: 'onlycars-c1fd0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDoGgUpdRGLOYkVR1HsH3IWVmGLitTe2EM',
    appId: '1:778060752352:ios:1465372fffccea4208b785',
    messagingSenderId: '778060752352',
    projectId: 'onlycars-c1fd0',
    storageBucket: 'onlycars-c1fd0.firebasestorage.app',
    iosBundleId: 'com.onlycars.pro',
  );
}
